server:
  port: 8081

spring:
  profiles:
    active: local

#  jwt:
#    secret: hungrybird@$&

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        format_sql: true

